# version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: shared_nginx
    ports:
      - "80:80"  
      # - "8000:8000"
      # - "8001:8001"
      # # - "8002:8002"
      # - "8015:8015"
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - shared_infra
    restart: unless-stopped

  kafka-0:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka_broker
    hostname: kafka-0
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 0
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-0:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: abcdefghijklmnopqrstuv

      # Оптимизация для локальной разработки
      KAFKA_LOG_RETENTION_HOURS: 24
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - shared_infra
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.0
    container_name: kafka_ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: main_cluster
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-0:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    depends_on:
      kafka-0:
        condition: service_healthy
    networks:
      - shared_infra
    restart: unless-stopped

volumes:
  kafka_data:
    driver: local

networks:
  shared_infra:
    driver: bridge
    name: shared_infra
